language: python
python:
- '3.6'
- '3.7'
- '3.8'
- '3.9'
script:
- python -m unittest discover -v
deploy:
  provider: pypi
  user: __token__
  password:
    secure: so79SXUxq0fmSEIe85Zy90qKLOjx1nLnXpM/mmGvGNZuHyfwGNymRqKmiKsoIE1mexzo1LsUWatfy+Jv6yDkDNkVEGAnobwGifUuPC4XPkUwDOnhDE0o3e6HdpyWafRxmrb8pTpuNJduqzUhgD9+/aVX8TLPeMjA+azO5S2WuIgBeb/sh/jXA9GizDicEzXe6bIzieTb880+sfAUHDKFQRDk04iiqfmp6jAxcdY3tMuPOfm/ZOPLs4GCXg1mBmnKtxbObrXAmDvn8pKRNxx39eI0C36pnE7/ItsRVU+B1P6xOE04Q7Q/8wXc1bcKPr56PAKOuSRiOLE7bE0uiwLr1DBHy6XSUBTJoXidHPLeefUvtFBm6OzBVnLoqtw4yHmq6Xj/V2dIwXfkSXnApg31n0s4zvTliMSSyEZp+KUHp/lsvyPMhF8ddw6WXebXYgZ12dTRXmD3Rdc+PPxcn397lF6iCpLWF8SKYCLB8b/SMv9LfE/N87c2LCzGykl6XTElR4MIi7W5N+NyMUgYvCq4fPhqdanVXqnScRoKJX0NeI9j6Qbh4w8QtfnXfnHrZYwNd9Hu/66DnGurQAqAQNCCsUfdkI1d4ZQTmYNKHL/Dx2X7MuBPH5bbcNI/zYtBjSbPBMaaxXHEwXDQGgi17EsS+SavL5D7PJiIaXxym4Dhn7E=
  on:
    branch: master
    python: 3.8
